routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'BerandaController@index')->name('beranda');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
Route::get('/syarat-ketentuan', ['as'=>'sdk', function(){
	return view('blog.syarat_ketentuan');
}]);
// Route::get('/product/create', 'ProductController@create');

// Route::post('/product', 'ProductController@store');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::put('/dashboard', 'ProfilController@update')->name('profil.edit');

Route::get('/product/{menu}/{id}/detail', 'ProductController@detail')->name('product.detail');
Route::get('/product/{menu}/{id}/order', 'ProductController@order')->name('product.order');
Route::put('/product/{id}/checkout', 'ProductController@checkout')->name('product.checkout');

Route::get('/dapur/{dapur_name}', 'DapurController@show')->name('dapur.show');

Route::get('login/{sevice}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{sevice}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/kecamatan', 'ProductController@kecamatanAjax')->name('kecamatan');

Route::resource('orders', 'OrdersController')->except([
    'index', 'create'
]);

Route::get('search', 'SearchController@search')->name('search');


Route::group([
	'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => ['auth','admin'],
    'as'         => 'admin.'
], function(){
	Route::get('/','AdminController@dashboard')->name('dashboard');
	Route::get('users','AdminController@users')->name('users');
	Route::get('users/data', 'UserListController@users')->name('users.data');
	Route::delete('users/{id}', 'UserListController@destroy')->name('users.delete');

	Route::get('pesanan','AdminController@pesanan')->name('pesanan');
	Route::get('pesanan/data','DaftarPesananController@pesanan')->name('pesanan.data');
	Route::get('pesanan/{id}', 'DaftarPesananController@show')->name('pesanan.show');
	Route::patch('pesanan/{id}', 'DaftarPesananController@markasdone')->name('pesanan.markasdone');
	Route::delete('pesanan/{id}', 'DaftarPesananController@destroy')->name('pesanan.delete');

	// Route::get('dapur','AdminController@dapur')->name('dapur');
	Route::resource('dapur', 'DapurController');
	Route::get('dapur/data/json','DapurController@dapurs')->name('dapur.data');
});

resources/views/admin/_action-pesanan.blade.php
<div class="text-right d-flex justify-content-around ">
	@if(!$isdone)
	<a href="{{ $url_markasdone }}" class="btn-markasdone mx-1" data-order-number="{{ $order->order_number }}"><h3><i class="fa fa-check text-success"></i></h3></a>
	@endif
	<a href="{{ $url_show }}" class="btn-show mx-1" data-id="{{ $order->id }}"><h3><i class="fa fa-list text-primary"></i></h3></a>
	<a href="{{ $url_destroy }}" class="btn-delete mx-1" title="{{ $order->name }}"><h3><i class="fa fa-trash text-danger"></i></h3></a>
</div>

resources/views/admin/_action-user.blade.php
<div class="text-right d-flex justify-content-around ">
	<a href="{{ $url_destroy }}" class="btn-delete mx-1" title="{{ $user->name }}" tipe="{{ $user->tipe }}"><h3><i class="fa fa-trash text-danger"></i></h3></a>
</div>

resources/views/admin/_action.blade.php
<div class="text-right d-flex justify-content-around ">
	<a href="{{ $url_show }}" class="btn-show mx-1" title="Detail: {{ $item->name }}"><h3><i class="fas fa-bars text-primary" ></i></h3></a>
	<a href="{{ $url_edit }}" class="modal-show edit mx-1" title="Edit {{ $item->name }}"><h3><i class="icon-pencil text-warning"></i></h3></a>
	<a href="{{ $url_destroy }}" class="btn-delete mx-1" title="{{ $item->name }}"><h3><i class="icon-trash text-danger"></i></h3></a>
</div>

resources/views/admin/_action_dapur.blade.php
<div class="text-right d-flex justify-content-around ">
	<a href="{{ $url_edit }}" class="btn-show mx-1"><h3><i class="fa fa-edit text-primary"></i></h3></a>
	<a href="{{ $url_destroy }}" class="btn-delete mx-1" title="{{ $title }}"><h3><i class="fa fa-trash text-danger"></i></h3></a>
</div>

resources/views/admin/_form_dapur.blade.php
{!! Form::model($dapur, [
	'route' => $dapur->exists ? ['admin.dapur.update', $dapur->id] : 'admin.dapur.store',
	'method' => $dapur->exists ? 'PATCH' : "POST",
	'enctype' => "multipart/form-data",
]) !!}
<div class="form-group">
	<label for="" class="bmd-label-floating">Nama</label>
	{!! Form::text('nama', null, ['class'=>'form-control', 'id'=>'code'])!!}
</div>
<div class="form-group ">
	<label for="" class="bmd-label-floating">Alamat</label>
	{!! Form::text('alamat', null, ['class'=>'form-control', 'id'=>'name'])!!}
</div>
<div class="form-group ">
	<label for="" class="bmd-label-floating">Deskripsi</label>
	{!! Form::text('deskripsi', null, ['class'=>'form-control', 'id'=>'deskripsi'])!!}
</div>
<div class="form-group ">
	<label for="" class="bmd-label-floating">Kuota</label>
	{!! Form::number('kuota', null, ['class'=>'form-control', 'id'=>'kuota'])!!}
</div>
<div class="form-group ">
	<label for="" class="bmd-label-floating">Lokasi</label>
	{!! Form::text('lokasi', null, ['class'=>'form-control', 'id'=>'lokasi'])!!}
</div>
<div class="">
	<label for="" class="bmd-label-floating">Foto</label>
	<br>
	{!! Form::file('foto', ['id'=>'foto'])!!}
</div>
<br>
<div class="">
	<label for="" class="bmd-label-floating">Foto Header</label>
	<br>
	{!! Form::file('foto_header',['id'=>'foto_header'])!!}
</div>
{!! Form::submit($button,['class'=>'btn btn-success'])!!}
{!! Form::close() !!}

resources/views/admin/dapur.blade.php
@extends('admin.master')
@section('title', 'Daftar Pesanan | Admin JuruDapur')
@section('subtitle', 'Daftar Pesanan')
@push('style')
	
@endpush
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header card-header-primary card-header-icon">
				<div class="card-icon">
					<i class="material-icons">assignment</i>
				</div>
				<h4 class="card-title">Daftar Dapur</h4>
			</div>
			<div class="card-body">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">
							<a href="{{ route('admin.dapur.create') }}" class="btn btn-success pull-right modal-show btn-add-dapur"
								style="margin-top: -8px;" title="Add Item"><i class="icon-plus"></i> Tambah Dapur</a>
						</h3>
					</div>
					<div class="panel-body">
						<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" scoped>
						<link href="{{ asset('vendor/datatables/datatables.min.css') }}" rel="stylesheet" scoped>
						<table id="datatable" class="table table-striped table-no-bordered dataTable dtr-inline"
							style="width:100%">
							<thead>
								<tr>
									<th>No</th>
									<th>Nama</th>
									<th>Alamat</th>
									<th>Deskripsi</th>
									<th>Kuota</th>
									<th>Kecamatan</th>
									<th>Foto</th>
									<th>Foto Header</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
							<tfoot>
								<tr>
									<th>No</th>
									<th>Nama</th>
									<th>Alamat</th>
									<th>Deskripsi</th>
									<th>Kuota</th>
									<th>Kecamatan</th>
									<th>Foto</th>
									<th>Foto Header</th>
									<th>Action</th>
								</tr>
							</tfoot>
						</table>
						@include('admin._modal')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('vendor/datatables/datatables.min.js') }}"></script>
<script>
	$(document).ready(function () {
		let csrf_token = $('meta[name="csrf-token"]').attr('content');
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{route('admin.dapur.data') }}",
            columns: [
                {data: 'DT_RowIndex',name: 'id', className: 'text-center'},
                {data: 'nama',name: 'nama'},
                {data: 'alamat',name: 'alamat'},
                {data: 'deskripsi',name: 'deskripsi'},
                {data: 'kuota',name: 'kuota', mRender: function(data){
					return data == null ? "0" : data;
				}},
				{data: 'lokasi',name: 'lokasi'},
                {data: 'foto',name: 'foto', mRender: function(data){
					return `<img class="img-thumbnail" src="/uploads/img/dapur/`+data+`" alt="">`;
				}},
                {data: 'foto_header',name: 'foto_header', mRender: function(data){
					return `<img class="img-thumbnail" src="/uploads/img/dapur/header/`+data+`" alt="">`;
				}},
                {data: 'action',name: 'action'}
            ]
        });
        $('body').on('click', '.btn-delete', function (event) {
            event.preventDefault();
            var me = $(this),
                url = me.attr('href'),
                title = me.attr('title');

            swal({
                title: 'Anda yakin untuk menghapus ' + title + ' ?',
                text: 'Anda tidak dapat mengurungkan tindakan ini.',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus saja'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            '_method': 'DELETE',
                            '_token': csrf_token
                        },
                        success: function (response) {
                            $('#datatable').DataTable().ajax.reload();
                            swal({
                                type: 'success',
                                title: 'Berhasil!',
                                text: 'Data telah terhapus!',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        },
                        error: function (xhr) {
                            swal({
                                type: 'error',
                                title: 'Oops...',
                                text: 'Terjadi kesalahan!'
                            });
                        }
                    });
                }
            });
        });


        $('.sidebar-wrapper .nav-item:eq(3)').addClass('active');
    });
</script>
@endsection

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>
        @yield('title', config('app.name'))
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="{{ asset('material-dashboard/css/material-dashboard.css?v=2.1.1') }}" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="purple" data-background-color="white" data-image="{{ asset('material-dashboard/img/sidebar-1.jpg') }} ">
            <div class="logo">
                <a href="{{ config('app.url') }}" class="simple-text logo-normal">
                    JuruDapur
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.dashboard') }}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('admin.users') }}">
                            <i class="material-icons">person</i>
                            <p>Daftar Pengguna</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('admin.pesanan') }}">
                            <i class="material-icons">person</i>
                            <p>Daftar Pesanan</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('admin.dapur.index') }}">
                            <i class="material-icons">person</i>
                            <p>Daftar Dapur</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="#pablo">@yield('subtitle',config('app.name'))</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <form class="navbar-form d-none">
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                    <i class="material-icons">search</i>
                                    <div class="ripple-container"></div>
                                </button>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">person</i>
                                    <p class="d-lg-none d-md-block">
                                        Account
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                                    <a class="dropdown-item" href="{{route('dashboard')}}">Profile</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    @yield('content')
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="float-left">
                        <ul>
                            <li>
                                <a href="https://www.creative-tim.com">
                                    Creative Tim
                                </a>
                            </li>
                            <li>
                                <a href="https://creative-tim.com/presentation">
                                    About Us
                                </a>
                            </li>
                            <li>
                                <a href="http://blog.creative-tim.com">
                                    Blog
                                </a>
                            </li>
                            <li>
                                <a href="https://www.creative-tim.com/license">
                                    Licenses
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright float-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())

                        </script>, made with <i class="material-icons">favorite</i> by
                        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <div class="fixed-plugin">
        <div class="dropdown show-dropdown">
            <a href="#" data-toggle="dropdown">
                <i class="fa fa-cog fa-2x"> </i>
            </a>
            <ul class="dropdown-menu">
                <li class="header-title"> Sidebar Filters</li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger active-color">
                        <div class="badge-colors ml-auto mr-auto">
                            <span class="badge filter badge-purple" data-color="purple"></span>
                            <span class="badge filter badge-azure" data-color="azure"></span>
                            <span class="badge filter badge-green" data-color="green"></span>
                            <span class="badge filter badge-warning" data-color="orange"></span>
                            <span class="badge filter badge-danger" data-color="danger"></span>
                            <span class="badge filter badge-rose active" data-color="rose"></span>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="header-title">Images</li>
                <li class="active">
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="{{ asset('material-dashboard/img/sidebar-1.jpg') }}" alt="">
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="{{ asset('material-dashboard/img/sidebar-2.jpg') }}" alt="">
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="{{ asset('material-dashboard/img/sidebar-3.jpg') }}" alt="">
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="{{ asset('material-dashboard/img/sidebar-4.jpg') }}" alt="">
                    </a>
                </li>
                <li class="button-container">
                    <a href="https://www.creative-tim.com/product/material-dashboard" target="_blank" class="btn btn-primary btn-block">Free
                        Download</a>
                </li>
                <!-- <li class="header-title">Want more components?</li>
            <li class="button-container">
                <a href="https://www.creative-tim.com/product/material-dashboard-pro" target="_blank" class="btn btn-warning btn-block">
                  Get the pro version
                </a>
            </li> -->
                <li class="button-container">
                    <a href="https://demos.creative-tim.com/material-dashboard/docs/2.1/getting-started/introduction.html"
                        target="_blank" class="btn btn-default btn-block">
                        View Documentation
                    </a>
                </li>
                <li class="button-container github-star">
                    <a class="github-button" href="https://github.com/creativetimofficial/material-dashboard" data-icon="octicon-star"
                        data-size="large" data-show-count="true" aria-label="Star ntkme/github-buttons on GitHub">Star</a>
                </li>
                <li class="header-title">Thank you for 95 shares!</li>
                <li class="button-container text-center">
                    <button id="twitter" class="btn btn-round btn-twitter"><i class="fa fa-twitter"></i> &middot; 45</button>
                    <button id="facebook" class="btn btn-round btn-facebook"><i class="fa fa-facebook-f"></i> &middot;
                        50</button>
                    <br>
                    <br>
                </li>
            </ul>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="{{ asset('material-dashboard/js/core/jquery.min.js') }}"></script>
    <script src="{{ asset('material-dashboard/js/core/popper.min.js') }}"></script>
    <script src="{{ asset('material-dashboard/js/core/bootstrap-material-design.min.js') }}"></script>
    <script src="{{ asset('material-dashboard/js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>

    <script src="{{ asset('material-dashboard/js/plugins/moment.min.js') }}"></script>

    <script src="{{ asset('material-dashboard/js/plugins/sweetalert2.js') }}"></script>

    {{-- <script src="{{ asset('material-dashboard/js/plugins/jquery.validate.min.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/jquery.bootstrap-wizard.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/bootstrap-selectpicker.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/bootstrap-datetimepicker.min.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/jquery.dataTables.min.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/bootstrap-tagsinput.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/jasny-bootstrap.min.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/fullcalendar.min.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/jquery-jvectormap.js') }}"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/nouislider.min.js') }}"></script> --}}

    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js'"></script> --}}

    {{-- <script src="{{ asset('material-dashboard/js/plugins/arrive.min.js') }}"></script> --}}

    {{-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script> --}}

    <script src="{{ asset('material-dashboard/js/plugins/chartist.min.js') }}"></script>

    {{-- <script src="{{ asset('material-dashboard/js/plugins/bootstrap-notify.js') }}"></script> --}}

    <script src="{{ asset('material-dashboard/js/material-dashboard.js?v=2.1.1') }}" type="text/javascript"></script>

    @yield('scripts')
</body>

</html>

resources/views/admin/pesanan.blade.php
@extends('admin.master')
@section('title', 'Daftar Pesanan | Admin JuruDapur')
@section('subtitle', 'Daftar Pesanan')
@push('style')
	
@endpush
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header card-header-primary card-header-icon">
				<div class="card-icon">
					<i class="material-icons">assignment</i>
				</div>
				<h4 class="card-title">Daftar Pesanan</h4>
			</div>
			<div class="card-body">
				<div class="panel panel-primary">
					<div class="panel-heading">
						
					</div>
					<div class="panel-body">
						<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" scoped>
						<link href="{{ asset('vendor/datatables/datatables.min.css') }}" rel="stylesheet" scoped>
						<table id="datatable" class="table table-striped table-no-bordered dataTable dtr-inline"
							style="width:100%">
							<thead>
								<tr>
									<th>No</th>
									<th>Nomor Pemesanan</th>
									<th>Nama</th>
									<th>Tipe</th>
									<th>Menu</th>
									<th>Dapur</th>
									<th>Kuantitas</th>
									<th>Tanggal Pesan</th>
									<th>Lokasi Pembayaran</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
							<tfoot>
								<tr>
									<th>No</th>
									<th>Nomor Pemesanan</th>
									<th>Nama</th>
									<th>Tipe</th>
									<th>Menu</th>
									<th>Dapur</th>
									<th>Kuantitas</th>
									<th>Tanggal Pesan</th>
									<th>Lokasi Pembayaran</th>
									<th>Action</th>
								</tr>
							</tfoot>
						</table>
						@include('admin._modal')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('vendor/datatables/datatables.min.js') }}"></script>
<script>
	$(document).ready(function () {
		let csrf_token = $('meta[name="csrf-token"]').attr('content');
        $('#datatable').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{route('admin.pesanan.data') }}",
            columns: [
                {data: 'DT_RowIndex',name: 'id', className: 'text-center'},
                {data: 'order_number',name: 'order_number'},
                {data: 'user.name',name: 'user.name'},
                {data: 'menu.tipe',name: 'menu.tipe'},
                {data: 'menu.nama',name: 'menu.nama'},
				{data: 'dapur.nama',name: 'dapur.nama'},
                {data: 'quantity',name: 'quantity'},
                {data: 'delivery_date',name: 'delivery_date'},
                {data: 'payment_location',name: 'payment_location'},
                {data: 'action',name: 'action'}
            ]
        });
	
		$('body').on('click', '.btn-markasdone', function (event) {
			event.preventDefault();
			let me = $(this),
			orderNumber = me.attr('data-order-number'),
			url = me.attr('href');
			swal({
                title: 'Apakah Anda yakin ingin menandai ' + orderNumber + ' telah selesai?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            '_method': 'PATCH',
                            '_token': csrf_token
                        },
                        success: function (response) {
                            $('#datatable').DataTable().ajax.reload();
                            swal({
                                type: 'success',
                                title: 'Success!',
                                text: 'Data has been deleted!',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        },
                        error: function (xhr) {
                            swal({
                                type: 'error',
                                title: 'Oops...',
                                text: 'Something went wrong!'
                            });
                        }
                    });
                }
            });
		});
		$('body').on('click', '.btn-show', function (event) {
			event.preventDefault();

			let me = $(this),
				id = me.attr('data-id')
				url = me.attr('href');

			$.ajax({
				dataType : 'html',
				url : url,
				success : function(response){
					$('#modal').modal('show');
					$('#modal-title').text('Data Pemesanan');
					$('#modal-btn-save').addClass('d-none');
					$('#modal-body').html(response);
				},
				failed : function(error){
					swal({
						title: 'Error',
						text: 'Something error!',
						type: 'error'
					});
				}
			})
		});
        $('body').on('click', '.btn-delete', function (event) {
            event.preventDefault();
            var me = $(this),
                url = me.attr('href'),
                title = me.attr('title'),
				tipe = me.attr('tipe');

			if(tipe == 1){
				swal({
					title: 'You won\'t be able to delete Admin'
				});
				return;
			}

            swal({
                title: 'Anda yakin untuk menghapus ' + title + ' ?',
                text: 'Anda tidak dapat mengurungkan tindakan ini.',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus saja'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            '_method': 'DELETE',
                            '_token': csrf_token
                        },
                        success: function (response) {
                            $('#datatable').DataTable().ajax.reload();
                            swal({
                                type: 'success',
                                title: 'Berhasil!',
                                text: 'Data telah terhapus!',
                                showConfirmButton: false,
                                timer: 2000
                            });
                        },
                        error: function (xhr) {
                            swal({
                                type: 'error',
                                title: 'Oops...',
                                text: 'Terjadi kesalahan!'
                            });
                        }
                    });
                }
            });
        });


        $('.sidebar-wrapper .nav-item:eq(2)').addClass('active');
    });
</script>
@endsection